<tsd:PluginWindowBase
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:LSTK.Frame"
             xmlns:tsd="clr-namespace:Tekla.Structures.Dialog;assembly=Tekla.Structures.Dialog"
             xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog"
             x:Class="LSTK.Frame.MainWindow"
             mc:Ignorable="d" 
             d:DesignHeight="600"
             Title="{tsd:Loc albl_LSTK_Frame_plug-in}" Height="750" Width="1000
    " HorizontalAlignment="Stretch">
    <Grid HorizontalAlignment="Stretch" Margin="0,0,0,0">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" MinHeight="48" />
            <RowDefinition Height="2*"/>
            <RowDefinition Height="0.5*"/>
            <RowDefinition Height="Auto" MinHeight="48"/>
        </Grid.RowDefinitions>
        <UIControls:WpfSaveLoad Grid.Row="0" HorizontalAlignment="Stretch" Margin="0,0,0,0" VerticalAlignment="Top" Height="51" />
        <Grid Grid.Row="1">
            <Grid.RowDefinitions>
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
            </Grid.RowDefinitions>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="0.5*"/>
                <ColumnDefinition Width="0.5*"/>
                <ColumnDefinition Width="0.5*"/>
            </Grid.ColumnDefinitions>
            <StackPanel Grid.Row="2" Orientation="Horizontal">
                <Label x:Name="label_Height_Columns" Content="{tsd:Loc albl_Height_Columns}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="heightColumns" />
                <TextBox
                    x:Name="tb_Height_Columns"
                    Width="120"
                    Height="23"
                    Text="{Binding HeightColumns, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="1"  Grid.Row="0" Orientation="Horizontal">
                <Label x:Name="label_Height_RoofRidge" Content="{tsd:Loc albl_Height_RoofRidge}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="heightRoofRidge" />
                <TextBox
                    x:Name="tb_Height_RoofRidge"
                    Width="120"
                    Height="23"
                    Text="{Binding HeightRoofRidge, Mode=TwoWay}"/>
            </StackPanel>


            <StackPanel Grid.Column="2" Grid.Row="6" Orientation="Horizontal">
                <Label x:Name="label_PartName_Group" Content="{tsd:Loc albl_PartName_Group}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="partNameGroup"/>
                <TextBox x:Name="tb_PartName_Group" Width="120" Height="23" VerticalAlignment="Center" Text="{Binding PartNameGroup, Mode=TwoWay}" TextWrapping="Wrap"  />
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="7" Orientation="Horizontal">
                <Label x:Name="label_Profile_Group" Content="{tsd:Loc albl_Profile_Group}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="profileGroup" />
                <TextBox
                    x:Name="tb_Profile_Group"
                    Width="120"
                    Height="23"
                    Text="{Binding ProfileGroup, Mode=TwoWay}"/>
                <UIControls:WpfProfileCatalog x:Name="profileCatalogGroup" HorizontalAlignment="Left" VerticalAlignment="Center" SelectClicked="profileCatalogGroup_SelectClicked" SelectionDone="profileCatalogGroup_SelectionDone"/>
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="8" Orientation="Horizontal">
                <Label x:Name="label_Material_Group" Content="{tsd:Loc albl_Material_Group}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="materialGroup" />
                <TextBox
                    x:Name="tb_Material_Group"
                    Width="120"
                    Height="23"
                    Text="{Binding MaterialGroup, Mode=TwoWay}"/>
                <UIControls:WpfMaterialCatalog x:Name="materialCatalogGroup" HorizontalAlignment="Left" VerticalAlignment="Center" SelectClicked="WpfMaterialCatalogGroup_SelectClicked" SelectionDone="WpfMaterialCatalogGroup_SelectionDone"/>
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="9" Orientation="Horizontal">
                <Label x:Name="label_Class_Group" Content="{tsd:Loc albl_Class_Group}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="classGroup" />
                <TextBox
                    x:Name="tb_Class_Group"
                    Width="120"
                    Height="23"
                    Text="{Binding ClassGroup, Mode=TwoWay}" Margin="0,4,0,0" VerticalAlignment="Top"/>
            </StackPanel>
            <StackPanel Grid.Column="1"  Grid.Row="1" Orientation="Horizontal">
                <Label x:Name="label_Height_RoofBottom" Content="{tsd:Loc albl_Height_RoofBottom}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="heightRoofBottom" />
                <TextBox
                    x:Name="tb_Height_RoofBottom"
                    Width="120"
                    Height="23"
                    Text="{Binding HeightRoofBottom, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="0" Grid.Row="1" Orientation="Horizontal">
                <Label x:Name="label_Bay" Content="{tsd:Loc albl_Bay}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="bay" />
                <TextBox
                    x:Name="tb_Bay"
                    Width="120"
                    Height="23"
                    Text="{Binding Bay, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="0" Grid.Row="0" Orientation="Horizontal">
                <Label x:Name="label_FrameOption" Content="{tsd:Loc albl_FrameOption}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="frameOption"/>
                <ComboBox x:Name="cmb_FrameOption" Height="25" Width="120" ItemsSource="{Binding FrameOptionList}" SelectedItem ="{Binding FrameOption, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="0" Orientation="Horizontal">
                <Label x:Name="label_TopChordLineOption" Content="{tsd:Loc albl_TopChordLineOption}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="topChordLineOption"/>
                <ComboBox x:Name="cmb_TopChordLineOption" Height="25" Width="120" ItemsSource="{Binding TopChordLineOptionList}" SelectedItem ="{Binding TopChordLineOption, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="1" Orientation="Horizontal">
                <Label x:Name="label_BottomChordLineOption" Content="{tsd:Loc albl_BottomChordLineOption}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="bottomChordLineOption"/>
                <ComboBox x:Name="cmb_BottomChordLineOption" Height="25" Width="120" ItemsSource="{Binding ColumnLineOptionList}" SelectedItem ="{Binding BottomChordLineOption, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="2" Orientation="Horizontal">
                <Label x:Name="label_ColumnLineOption" Content="{tsd:Loc albl_ColumnLineOption}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="columnLineOption"/>
                <ComboBox x:Name="cmb_ColumnLineOption" Height="25" Width="120" ItemsSource="{Binding ColumnLineOptionList}" SelectedItem ="{Binding ColumnLineOption, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="3" Orientation="Horizontal">
                <Label x:Name="label_CentralColumnLineOption" Content="{tsd:Loc albl_CentralColumnLineOption}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="centralColumnLineOption"/>
                <ComboBox x:Name="cmb_CentralColumnLineOption" Height="25" Width="120" ItemsSource="{Binding CentralColumnLineOptionList}" SelectedItem ="{Binding CentralColumnLineOption, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="4" Orientation="Horizontal">
                <Label x:Name="label_DoubleProfileOption" Content="{tsd:Loc albl_DoubleProfileOption}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="doubleProfileOption"/>
                <ComboBox x:Name="cmb_DoubleProfileOption" Height="25" Width="120" ItemsSource="{Binding DoubleProfileOptionList}" SelectedItem ="{Binding DoubleProfileOption, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="5" Orientation="Horizontal">
                <Label x:Name="label_ProfileGap" Content="{tsd:Loc albl_ProfileGap}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="profileGap"/>
                <TextBox x:Name="tb_ProfileGap" Width="120" Height="23" VerticalAlignment="Center" Text="{Binding ProfileGap, Mode=TwoWay}" TextWrapping="Wrap"  />
            </StackPanel>
            <StackPanel Grid.Column="1" Grid.Row="2" Orientation="Horizontal">
                <Label x:Name="label_Panels" Content="{tsd:Loc albl_Panels}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="panels" />
                <TextBox
                    x:Name="tb_Panels"
                    Width="120"
                    Height="23"
                    Text="{Binding Panels, Mode=TwoWay}"/>
            </StackPanel>
            <Button Grid.Column="2" Grid.Row="11" x:Name="b_schema" Content="Build Schema" Click="b_schema_Click"/>
            <Button Grid.Column="2" Grid.Row="10" x:Name="b_acceptAttribute" Content="Accept attributes" Width="165" HorizontalAlignment="Left" Click="b_acceptAttribute_Click"/>
            <Button Grid.Column="2" Grid.Row="10" x:Name="b_getAttribute" Content="Get attributes" Width="165" HorizontalAlignment="Right" Click="b_acceptAttribute_Click"/>
            <StackPanel Grid.Column="2" Grid.Row="7" Orientation="Horizontal" Visibility="Hidden">
                <Label x:Name="label_AttributeGroups" Content="{tsd:Loc albl_AttributeGroups}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="attributeGroups" />
                <TextBox
                    x:Name="tb_AttributeGroups"
                    Width="120"
                    Height="23"
                    Text="{Binding AttributeGroups, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="8" Orientation="Horizontal" Visibility="Hidden">
                <Label x:Name="label_ElementPrototypes" Content="{tsd:Loc albl_ElementPrototypes}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="elementPrototypes" />
                <TextBox
                    x:Name="tb_ElementPrototypes"
                    Width="120"
                    Height="23"
                    Text="{Binding ElementDataPrototypes, Mode=TwoWay}"/>
            </StackPanel>

        </Grid>
        <Grid x:Name="g_schema"  Grid.Row="2" Width="990" Height="110">
            <!--<Path Stroke="Blue" MouseDown="Path_MouseDown" StrokeThickness="5">
                <Path.Data>
                    <LineGeometry StartPoint="0,0" EndPoint="200,130"/>
                </Path.Data>
            </Path>-->
        </Grid>
        <UIControls:WpfOkApplyModifyGetOnOffCancel
            Grid.Row="3"
            ApplyClicked="WPFOkApplyModifyGetOnOffCancel_ApplyClicked"
            CancelClicked="WPFOkApplyModifyGetOnOffCancel_CancelClicked"
            GetClicked="WPFOkApplyModifyGetOnOffCancel_GetClicked"
            ModifyClicked="WPFOkApplyModifyGetOnOffCancel_ModifyClicked"
            OkClicked="WPFOkApplyModifyGetOnOffCancel_OkClicked"
            OnOffClicked="WPFOkApplyModifyGetOnOffCancel_OnOffClicked" />
    </Grid>
</tsd:PluginWindowBase>
