<tsd:PluginWindowBase
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:LSTK.Frame"
             xmlns:tsd="clr-namespace:Tekla.Structures.Dialog;assembly=Tekla.Structures.Dialog"
             xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog"
             x:Class="LSTK.Frame.MainWindow"
             mc:Ignorable="d" 
             d:DesignHeight="600"
             Title="{tsd:Loc albl_LSTK_Frame_plug-in}" Height="700" Width="1000
    " HorizontalAlignment="Stretch">
    <Grid HorizontalAlignment="Stretch" Margin="0,0,0,0">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" MinHeight="48" />
            <RowDefinition/>
            <RowDefinition Height="Auto" MinHeight="48"/>
        </Grid.RowDefinitions>
        <UIControls:WpfSaveLoad Grid.Row="0" HorizontalAlignment="Stretch" Margin="0,0,0,0" VerticalAlignment="Top" Height="51" />
        <Grid Grid.Row="1">
            <Grid.RowDefinitions>
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />


            </Grid.RowDefinitions>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="0.5*"/>
                <ColumnDefinition Width="0.5*"/>
                <ColumnDefinition Width="0.5*"/>
            </Grid.ColumnDefinitions>
            <StackPanel Orientation="Horizontal">
                <Label x:Name="label_PartName_Columns" Content="{tsd:Loc albl_PartName_Columns}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="partNameColumns"/>
                <TextBox x:Name="tb_PartName_Columns" Width="120" Height="23" VerticalAlignment="Center" Text="{Binding PartNameColumns, Mode=TwoWay}" TextWrapping="Wrap"  />
            </StackPanel>
            <StackPanel Grid.Row="1" Orientation="Horizontal">
                <Label x:Name="label_Profile_Columns" Content="{tsd:Loc albl_Profile_Columns}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="profileColumns" />
                <TextBox
                    x:Name="tb_Profile_Columns"
                    Width="120"
                    Height="23"
                    Text="{Binding ProfileColumns, Mode=TwoWay}"/>
                <UIControls:WpfProfileCatalog x:Name="profileCatalogColumns" HorizontalAlignment="Left" VerticalAlignment="Center" SelectClicked="WpfProfileCatalogColumns_SelectClicked" SelectionDone="WpfProfileCatalogColumns_SelectionDone"/>
            </StackPanel>
            <StackPanel Grid.Row="2" Orientation="Horizontal">
                <Label x:Name="label_Material_Columns" Content="{tsd:Loc albl_Material_Columns}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="materialColumns" />
                <TextBox
                    x:Name="tb_Material_Columns"
                    Width="120"
                    Height="23"
                    Text="{Binding MaterialColumns, Mode=TwoWay}"/>
                <UIControls:WpfMaterialCatalog x:Name="materialCatalogColumns" HorizontalAlignment="Left" VerticalAlignment="Center" SelectClicked="WpfMaterialCatalogColumns_SelectClicked" SelectionDone="WpfMaterialCatalogColumns_SelectionDone"/>
            </StackPanel>
            <StackPanel Grid.Row="3" Orientation="Horizontal">
                <Label x:Name="label_Class_Columns" Content="{tsd:Loc albl_Class_Columns}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="classColumns" />
                <TextBox
                    x:Name="tb_Class_Columns"
                    Width="120"
                    Height="23"
                    Text="{Binding ClassColumns, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Row="4" Orientation="Horizontal">
                <Label x:Name="label_Height_Columns" Content="{tsd:Loc albl_Height_Columns}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="heightColumns" />
                <TextBox
                    x:Name="tb_Height_Columns"
                    Width="120"
                    Height="23"
                    Text="{Binding HeightColumns, Mode=TwoWay}"/>
            </StackPanel>


            <StackPanel Grid.Row="6" Orientation="Horizontal">
                <Label x:Name="label_PartName_TopChord" Content="{tsd:Loc albl_PartName_TopChord}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="partNameTopChord"/>
                <TextBox x:Name="tb_PartName_TopChord" Width="120" Height="23" VerticalAlignment="Center" Text="{Binding PartNameTopChord, Mode=TwoWay}" TextWrapping="Wrap"  />
            </StackPanel>
            <StackPanel Grid.Row="7" Orientation="Horizontal">
                <Label x:Name="label_Profile_TopChord" Content="{tsd:Loc albl_Profile_TopChord}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="profileTopChord" />
                <TextBox
                    x:Name="tb_Profile_TopChord"
                    Width="120"
                    Height="23"
                    Text="{Binding ProfileTopChord, Mode=TwoWay}"/>
                <UIControls:WpfProfileCatalog x:Name="profileCatalogTopChord" HorizontalAlignment="Left" VerticalAlignment="Center" SelectClicked="profileCatalogTopChord_SelectClicked" SelectionDone="profileCatalogTopChord_SelectionDone"/>
            </StackPanel>
            <StackPanel Grid.Row="8" Orientation="Horizontal">
                <Label x:Name="label_Material_TopChord" Content="{tsd:Loc albl_Material_TopChord}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="materialTopChord" />
                <TextBox
                    x:Name="tb_Material_TopChord"
                    Width="120"
                    Height="23"
                    Text="{Binding MaterialTopChord, Mode=TwoWay}"/>
                <UIControls:WpfMaterialCatalog x:Name="materialCatalogTopChord" HorizontalAlignment="Left" VerticalAlignment="Center" SelectClicked="WpfMaterialCatalogTopChord_SelectClicked" SelectionDone="WpfMaterialCatalogTopChord_SelectionDone"/>
            </StackPanel>
            <StackPanel Grid.Row="9" Orientation="Horizontal">
                <Label x:Name="label_Class_TopChord" Content="{tsd:Loc albl_Class_TopChord}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="classTopChord" />
                <TextBox
                    x:Name="tb_Class_TopChord"
                    Width="120"
                    Height="23"
                    Text="{Binding ClassTopChord, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Row="10" Orientation="Horizontal">
                <Label x:Name="label_Height_RoofRidge" Content="{tsd:Loc albl_Height_RoofRidge}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="heightRoofRidge" />
                <TextBox
                    x:Name="tb_Height_RoofRidge"
                    Width="120"
                    Height="23"
                    Text="{Binding HeightRoofRidge, Mode=TwoWay}"/>
            </StackPanel>


            <StackPanel Grid.Column="1" Grid.Row="0" Orientation="Horizontal">
                <Label x:Name="label_PartName_Group" Content="{tsd:Loc albl_PartName_Group}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="partNameGroup"/>
                <TextBox x:Name="tb_PartName_Group" Width="120" Height="23" VerticalAlignment="Center" Text="{Binding PartNameGroup, Mode=TwoWay}" TextWrapping="Wrap"  />
            </StackPanel>
            <StackPanel Grid.Column="1" Grid.Row="1" Orientation="Horizontal">
                <Label x:Name="label_Profile_Group" Content="{tsd:Loc albl_Profile_Group}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="profileGroup" />
                <TextBox
                    x:Name="tb_Profile_Group"
                    Width="120"
                    Height="23"
                    Text="{Binding ProfileGroup, Mode=TwoWay}"/>
                <UIControls:WpfProfileCatalog x:Name="profileCatalogGroup" HorizontalAlignment="Left" VerticalAlignment="Center" SelectClicked="profileCatalogGroup_SelectClicked" SelectionDone="profileCatalogGroup_SelectionDone"/>
            </StackPanel>
            <StackPanel Grid.Column="1" Grid.Row="2" Orientation="Horizontal">
                <Label x:Name="label_Material_Group" Content="{tsd:Loc albl_Material_Group}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="materialGroup" />
                <TextBox
                    x:Name="tb_Material_Group"
                    Width="120"
                    Height="23"
                    Text="{Binding MaterialGroup, Mode=TwoWay}"/>
                <UIControls:WpfMaterialCatalog x:Name="materialCatalogGroup" HorizontalAlignment="Left" VerticalAlignment="Center" SelectClicked="WpfMaterialCatalogGroup_SelectClicked" SelectionDone="WpfMaterialCatalogGroup_SelectionDone"/>
            </StackPanel>
            <StackPanel Grid.Column="1" Grid.Row="3" Orientation="Horizontal">
                <Label x:Name="label_Class_Group" Content="{tsd:Loc albl_Class_Group}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="classGroup" />
                <TextBox
                    x:Name="tb_Class_Group"
                    Width="120"
                    Height="23"
                    Text="{Binding ClassGroup, Mode=TwoWay}"/>
            </StackPanel>


            <StackPanel Grid.Row="12" Orientation="Horizontal">
                <Label x:Name="label_PartName_BottomChord" Content="{tsd:Loc albl_PartName_BottomChord}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="partNameTopChord"/>
                <TextBox x:Name="tb_PartName_BottomChord" Width="120" Height="23" VerticalAlignment="Center" Text="{Binding PartNameBottomChord, Mode=TwoWay}" TextWrapping="Wrap"  />
            </StackPanel>
            <StackPanel Grid.Row="13" Orientation="Horizontal">
                <Label x:Name="label_Profile_BottomChord" Content="{tsd:Loc albl_Profile_BottomChord}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="profileBottomChord" />
                <TextBox
                    x:Name="tb_Profile_BottomChord"
                    Width="120"
                    Height="23"
                    Text="{Binding ProfileBottomChord, Mode=TwoWay}"/>
                <UIControls:WpfProfileCatalog x:Name="profileCatalogBottomChord" HorizontalAlignment="Left" VerticalAlignment="Center" SelectClicked="profileCatalogBottomChord_SelectClicked" SelectionDone="profileCatalogBottomChord_SelectionDone"/>
            </StackPanel>
            <StackPanel Grid.Row="14" Orientation="Horizontal">
                <Label x:Name="label_Material_BottomChord" Content="{tsd:Loc albl_Material_BottomChord}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="materialBottomChord" />
                <TextBox
                    x:Name="tb_Material_BottomChord"
                    Width="120"
                    Height="23"
                    Text="{Binding MaterialBottomChord, Mode=TwoWay}"/>
                <UIControls:WpfMaterialCatalog x:Name="materialCatalogBottomChord" HorizontalAlignment="Left" VerticalAlignment="Center" SelectClicked="WpfMaterialCatalogBottomChord_SelectClicked" SelectionDone="WpfMaterialCatalogBottomChord_SelectionDone"/>
            </StackPanel>
            <StackPanel Grid.Row="15" Orientation="Horizontal">
                <Label x:Name="label_Class_BottomChord" Content="{tsd:Loc albl_Class_BottomChord}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="classBottomChord" />
                <TextBox
                    x:Name="tb_Class_BottomChord"
                    Width="120"
                    Height="23"
                    Text="{Binding ClassBottomChord, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Row="16" Orientation="Horizontal">
                <Label x:Name="label_Height_RoofBottom" Content="{tsd:Loc albl_Height_RoofBottom}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="heightRoofBottom" />
                <TextBox
                    x:Name="tb_Height_RoofBottom"
                    Width="120"
                    Height="23"
                    Text="{Binding HeightRoofBottom, Mode=TwoWay}"/>
            </StackPanel>


            <StackPanel Grid.Column="2" Grid.Row="0" Orientation="Horizontal">
                <Label x:Name="label_Bay" Content="{tsd:Loc albl_Bay}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="bay" />
                <TextBox
                    x:Name="tb_Bay"
                    Width="120"
                    Height="23"
                    Text="{Binding Bay, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="1" Orientation="Horizontal">
                <Label x:Name="label_FrameOption" Content="{tsd:Loc albl_FrameOption}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="frameOption"/>
                <ComboBox x:Name="cmb_FrameOption" Height="25" Width="120" ItemsSource="{Binding FrameOptionList}" SelectedItem ="{Binding FrameOption, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="2" Orientation="Horizontal">
                <Label x:Name="label_TopChordLineOption" Content="{tsd:Loc albl_TopChordLineOption}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="topChordLineOption"/>
                <ComboBox x:Name="cmb_TopChordLineOption" Height="25" Width="120" ItemsSource="{Binding TopChordLineOptionList}" SelectedItem ="{Binding TopChordLineOption, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="3" Orientation="Horizontal">
                <Label x:Name="label_ColumnLineOption" Content="{tsd:Loc albl_ColumnLineOption}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="columnLineOption"/>
                <ComboBox x:Name="cmb_ColumnLineOption" Height="25" Width="120" ItemsSource="{Binding ColumnLineOptionList}" SelectedItem ="{Binding ColumnLineOption, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="2" Grid.Row="4" Orientation="Horizontal">
                <Label x:Name="label_Panels" Content="{tsd:Loc albl_Panels}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="panels" />
                <TextBox
                    x:Name="tb_Panels"
                    Width="120"
                    Height="23"
                    Text="{Binding Panels, Mode=TwoWay}"/>
            </StackPanel>
        </Grid>
        <UIControls:WpfOkApplyModifyGetOnOffCancel
            Grid.Row="2"
            ApplyClicked="WPFOkApplyModifyGetOnOffCancel_ApplyClicked"
            CancelClicked="WPFOkApplyModifyGetOnOffCancel_CancelClicked"
            GetClicked="WPFOkApplyModifyGetOnOffCancel_GetClicked"
            ModifyClicked="WPFOkApplyModifyGetOnOffCancel_ModifyClicked"
            OkClicked="WPFOkApplyModifyGetOnOffCancel_OkClicked"
            OnOffClicked="WPFOkApplyModifyGetOnOffCancel_OnOffClicked" />
    </Grid>
</tsd:PluginWindowBase>
