<tsd:PluginWindowBase
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:LSTK.Frame"
             xmlns:tsd="clr-namespace:Tekla.Structures.Dialog;assembly=Tekla.Structures.Dialog"
             xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog"
             x:Class="LSTK.Frame.MainWindow"
             mc:Ignorable="d" 
             d:DesignHeight="350"
             Title="{tsd:Loc albl_LSTK_Frame_plug-in}" Height="355" Width="700
    " HorizontalAlignment="Stretch">
    <Grid HorizontalAlignment="Stretch" Margin="0,0,0,0">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" MinHeight="48" />
            <RowDefinition/>
            <RowDefinition Height="Auto" MinHeight="48"/>
        </Grid.RowDefinitions>
        <UIControls:WpfSaveLoad Grid.Row="0" HorizontalAlignment="Stretch" Margin="0,0,0,0" VerticalAlignment="Top" Height="51" />
        <Grid Grid.Row="1">
            <Grid.RowDefinitions>
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
            </Grid.RowDefinitions>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="0.5*"/>
                <ColumnDefinition Width="0.5*"/>
            </Grid.ColumnDefinitions>
            <StackPanel Orientation="Horizontal">
                <Label x:Name="label_PartName" Content="{tsd:Loc albl_Part_name_columns}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="name"/>
                <TextBox x:Name="tb_PartNameColumns" Width="120" Height="23" VerticalAlignment="Center" Text="{Binding PartNameColumns, Mode=TwoWay}" TextWrapping="Wrap"  />
            </StackPanel>
            <StackPanel Grid.Row="1" Orientation="Horizontal">
                <Label x:Name="label_Profile_columns" Content="{tsd:Loc albl_Profile_columns}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="profile" />
                <TextBox
                    x:Name="tb_Profile_columns"
                    Width="120"
                    Height="23"
                    Text="{Binding ProfileColumns, Mode=TwoWay}"/>
                <UIControls:WpfProfileCatalog x:Name="profileCatalogColumns" HorizontalAlignment="Left" VerticalAlignment="Center" SelectClicked="WpfProfileCatalogColumns_SelectClicked" SelectionDone="WpfProfileCatalogColumns_SelectionDone"/>
            </StackPanel>
            <StackPanel Grid.Row="2" Orientation="Horizontal">
                <Label x:Name="label_Profile_topChord" Content="{tsd:Loc albl_Profile_topChord}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="profile_topChord" />
                <TextBox
                    x:Name="tb_Profile_topChord"
                    Width="120"
                    Height="23"
                    Text="{Binding ProfileTopChord, Mode=TwoWay}"/>
                <UIControls:WpfProfileCatalog x:Name="profileCatalogTopChord" HorizontalAlignment="Left" VerticalAlignment="Center" SelectClicked="profileCatalogTopChord_SelectClicked" SelectionDone="profileCatalogTopChord_SelectionDone"/>
            </StackPanel>
            <StackPanel Grid.Row="3" Orientation="Horizontal">
                <Label x:Name="label_HeightColumns" Content="{tsd:Loc albl_Height_columns}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="heightColumns" />
                <TextBox
                    x:Name="tb_HeightColumns"
                    Width="120"
                    Height="23"
                    Text="{Binding HeightColumns, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Row="4" Orientation="Horizontal">
                <Label x:Name="label_BayOverall" Content="{tsd:Loc albl_Bay_overall}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="bayOverall" />
                <TextBox
                    x:Name="tb_BayOverall"
                    Width="120"
                    Height="23"
                    Text="{Binding BayOverall, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Row="5" Orientation="Horizontal">
                <Label x:Name="label_RoofRidgeHeight" Content="{tsd:Loc albl_RoofRidgeHeight}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="roofRidgeHeight" />
                <TextBox
                    x:Name="tb_RoofRidgeHeight"
                    Width="120"
                    Height="23"
                    Text="{Binding RoofRidgeHeight, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Row="6" Orientation="Horizontal">
                <Label x:Name="label_RoofBottomHeight" Content="{tsd:Loc albl_RoofBottomHeight}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="roofBottomHeight" />
                <TextBox
                    x:Name="tb_RoofBottomHeight"
                    Width="120"
                    Height="23"
                    Text="{Binding RoofBottomHeight, Mode=TwoWay}"/>
            </StackPanel>
            <StackPanel Grid.Column="1" Orientation="Horizontal">
                <Label x:Name="label_FrameOption" Content="{tsd:Loc albl_FrameOption}" Height="30" Width="150"/>
                <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="frameOption"/>
                <ComboBox x:Name="cmb_FrameOption" Height="25" Width="150" ItemsSource="{Binding FrameOptionList}" SelectedItem ="{Binding FrameOption, Mode=TwoWay}"/>
            </StackPanel>
        </Grid>
        <UIControls:WpfOkApplyModifyGetOnOffCancel
            Grid.Row="2"
            ApplyClicked="WPFOkApplyModifyGetOnOffCancel_ApplyClicked"
            CancelClicked="WPFOkApplyModifyGetOnOffCancel_CancelClicked"
            GetClicked="WPFOkApplyModifyGetOnOffCancel_GetClicked"
            ModifyClicked="WPFOkApplyModifyGetOnOffCancel_ModifyClicked"
            OkClicked="WPFOkApplyModifyGetOnOffCancel_OkClicked"
            OnOffClicked="WPFOkApplyModifyGetOnOffCancel_OnOffClicked" />
    </Grid>
</tsd:PluginWindowBase>
